
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'A6KnxLedLabeled': typeof import("../../frontend/components/a6-knx-led-labeled.vue")['default']
    'A6KnxLed': typeof import("../../frontend/components/a6-knx-led.vue")['default']
    'AppCarousel': typeof import("../../frontend/components/app-carousel.vue")['default']
    'BannerCustomize': typeof import("../../frontend/components/banner-customize.vue")['default']
    'ContentList': typeof import("../../frontend/components/content-list.vue")['default']
    'ElementsColorBox': typeof import("../../frontend/components/elements/color-box.vue")['default']
    'ElementsLinkBox': typeof import("../../frontend/components/elements/link-box.vue")['default']
    'Icon360': typeof import("../../frontend/components/icon/360.vue")['default']
    'MailchimpForm': typeof import("../../frontend/components/mailchimp-form.vue")['default']
    'MottoQuado': typeof import("../../frontend/components/motto-quado.vue")['default']
    'Motto': typeof import("../../frontend/components/motto.vue")['default']
    'ProductSample': typeof import("../../frontend/components/product-sample.vue")['default']
    'SwitchDesigner': typeof import("../../frontend/components/switch-designer.vue")['default']
    'SystemDeviceItem': typeof import("../../frontend/components/system-device-item.vue")['default']
    'Viewer3dModal': typeof import("../../frontend/components/viewer-3d-modal.vue")['default']
    'Viewer3d': typeof import("../../frontend/components/viewer-3d.vue")['default']
    'CookieControl': typeof import("../../frontend/node_modules/@dargmuesli/nuxt-cookie-control/dist/runtime/components/CookieControl.vue")['default']
    'CookieIframe': typeof import("../../frontend/node_modules/@dargmuesli/nuxt-cookie-control/dist/runtime/components/CookieIframe.vue")['default']
    'XAccordion': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/accordion/Accordion.vue")['default']
    'XAccordionItem': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/accordion/AccordionItem.vue")['default']
    'XAlert': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/alert/Alert.vue")['default']
    'XAvatar': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/avatar/Avatar.vue")['default']
    'XBadge': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/badge/Badge.vue")['default']
    'XBreadcrumbs': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/breadcrumbs/Breadcrumbs.vue")['default']
    'XButton': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/button/Button.vue")['default']
    'XButtonGroup': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/button/ButtonGroup.vue")['default']
    'XCard': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/card/Card.vue")['default']
    'XCarousel': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/carousel/Carousel.vue")['default']
    'XCarouselSlide': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/carousel/CarouselSlide.vue")['default']
    'XCheckbox': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/checkbox/Checkbox.vue")['default']
    'XContainer': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/container/Container.vue")['default']
    'XDatepicker': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/datepicker/Datepicker.vue")['default']
    'XDivider': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/divider/Divider.vue")['default']
    'XDrawer': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/drawer/Drawer.vue")['default']
    'XForm': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/form/Form.vue")['default']
    'XFormGroup': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/formGroup/FormGroup.vue")['default']
    'XIcon': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/icon/Icon.vue")['default']
    'XImage': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/image/Image.vue")['default']
    'XInput': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/input/Input.vue")['default']
    'XInputFooter': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/inputFooter/InputFooter.vue")['default']
    'XLabel': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/label/Label.vue")['default']
    'XLink': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/link/Link.vue")['default']
    'XLoader': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/loader/Loader.vue")['default']
    'XMenu': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/menu/Menu.vue")['default']
    'XMenuItem': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/menu/MenuItem.vue")['default']
    'XModal': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/modal/Modal.vue")['default']
    'XNotifications': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/notifications/Notifications.vue")['default']
    'XPagination': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/pagination/Pagination.vue")['default']
    'XPaginationItem': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/pagination/PaginationItem.vue")['default']
    'XPopover': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/popover/Popover.vue")['default']
    'XPopoverContainer': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/popover/PopoverContainer.vue")['default']
    'XProgress': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/progress/Progress.vue")['default']
    'XQrCode': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/qrCode/QrCode.vue")['default']
    'XRadio': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/radio/Radio.vue")['default']
    'XScroll': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/scroll/Scroll.vue")['default']
    'XSelect': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/select/Select.vue")['default']
    'XSkeleton': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/skeleton/Skeleton.vue")['default']
    'XSlider': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/slider/Slider.vue")['default']
    'XSpacer': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/spacer/Spacer")['default']
    'XSpinner': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/spinner/Spinner.vue")['default']
    'XStepper': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/stepper/Stepper.vue")['default']
    'XTab': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/tab/Tab.vue")['default']
    'XTabGroup': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/tab/TabGroup.vue")['default']
    'XTable': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/table/Table.vue")['default']
    'XTableBody': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/table/TableBody")['default']
    'XTableCell': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/table/TableCell.vue")['default']
    'XTableHead': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/table/TableHead.vue")['default']
    'XTableHeader': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/table/TableHeader.vue")['default']
    'XTableRow': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/table/TableRow.vue")['default']
    'XTag': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/tag/Tag.vue")['default']
    'XTextarea': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/textarea/Textarea.vue")['default']
    'XThemeProvider': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/themeProvider/ThemeProvider.vue")['default']
    'XToggle': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/toggle/Toggle.vue")['default']
    'XTooltipToggleTip': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/tooltip/ToggleTip.vue")['default']
    'XTooltip': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/tooltip/Tooltip.vue")['default']
    'NuxtWelcome': typeof import("../../frontend/node_modules/nuxt/dist/app/components/welcome")['default']
    'NuxtLayout': typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../../frontend/node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../../frontend/node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../../frontend/node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtPage': typeof import("../../frontend/node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../../frontend/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyA6KnxLedLabeled': typeof import("../../frontend/components/a6-knx-led-labeled.vue")['default']
    'LazyA6KnxLed': typeof import("../../frontend/components/a6-knx-led.vue")['default']
    'LazyAppCarousel': typeof import("../../frontend/components/app-carousel.vue")['default']
    'LazyBannerCustomize': typeof import("../../frontend/components/banner-customize.vue")['default']
    'LazyContentList': typeof import("../../frontend/components/content-list.vue")['default']
    'LazyElementsColorBox': typeof import("../../frontend/components/elements/color-box.vue")['default']
    'LazyElementsLinkBox': typeof import("../../frontend/components/elements/link-box.vue")['default']
    'LazyIcon360': typeof import("../../frontend/components/icon/360.vue")['default']
    'LazyMailchimpForm': typeof import("../../frontend/components/mailchimp-form.vue")['default']
    'LazyMottoQuado': typeof import("../../frontend/components/motto-quado.vue")['default']
    'LazyMotto': typeof import("../../frontend/components/motto.vue")['default']
    'LazyProductSample': typeof import("../../frontend/components/product-sample.vue")['default']
    'LazySwitchDesigner': typeof import("../../frontend/components/switch-designer.vue")['default']
    'LazySystemDeviceItem': typeof import("../../frontend/components/system-device-item.vue")['default']
    'LazyViewer3dModal': typeof import("../../frontend/components/viewer-3d-modal.vue")['default']
    'LazyViewer3d': typeof import("../../frontend/components/viewer-3d.vue")['default']
    'LazyCookieControl': typeof import("../../frontend/node_modules/@dargmuesli/nuxt-cookie-control/dist/runtime/components/CookieControl.vue")['default']
    'LazyCookieIframe': typeof import("../../frontend/node_modules/@dargmuesli/nuxt-cookie-control/dist/runtime/components/CookieIframe.vue")['default']
    'LazyXAccordion': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/accordion/Accordion.vue")['default']
    'LazyXAccordionItem': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/accordion/AccordionItem.vue")['default']
    'LazyXAlert': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/alert/Alert.vue")['default']
    'LazyXAvatar': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/avatar/Avatar.vue")['default']
    'LazyXBadge': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/badge/Badge.vue")['default']
    'LazyXBreadcrumbs': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/breadcrumbs/Breadcrumbs.vue")['default']
    'LazyXButton': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/button/Button.vue")['default']
    'LazyXButtonGroup': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/button/ButtonGroup.vue")['default']
    'LazyXCard': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/card/Card.vue")['default']
    'LazyXCarousel': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/carousel/Carousel.vue")['default']
    'LazyXCarouselSlide': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/carousel/CarouselSlide.vue")['default']
    'LazyXCheckbox': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/checkbox/Checkbox.vue")['default']
    'LazyXContainer': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/container/Container.vue")['default']
    'LazyXDatepicker': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/datepicker/Datepicker.vue")['default']
    'LazyXDivider': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/divider/Divider.vue")['default']
    'LazyXDrawer': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/drawer/Drawer.vue")['default']
    'LazyXForm': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/form/Form.vue")['default']
    'LazyXFormGroup': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/formGroup/FormGroup.vue")['default']
    'LazyXIcon': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/icon/Icon.vue")['default']
    'LazyXImage': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/image/Image.vue")['default']
    'LazyXInput': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/input/Input.vue")['default']
    'LazyXInputFooter': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/inputFooter/InputFooter.vue")['default']
    'LazyXLabel': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/label/Label.vue")['default']
    'LazyXLink': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/link/Link.vue")['default']
    'LazyXLoader': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/loader/Loader.vue")['default']
    'LazyXMenu': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/menu/Menu.vue")['default']
    'LazyXMenuItem': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/menu/MenuItem.vue")['default']
    'LazyXModal': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/modal/Modal.vue")['default']
    'LazyXNotifications': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/notifications/Notifications.vue")['default']
    'LazyXPagination': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/pagination/Pagination.vue")['default']
    'LazyXPaginationItem': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/pagination/PaginationItem.vue")['default']
    'LazyXPopover': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/popover/Popover.vue")['default']
    'LazyXPopoverContainer': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/popover/PopoverContainer.vue")['default']
    'LazyXProgress': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/progress/Progress.vue")['default']
    'LazyXQrCode': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/qrCode/QrCode.vue")['default']
    'LazyXRadio': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/radio/Radio.vue")['default']
    'LazyXScroll': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/scroll/Scroll.vue")['default']
    'LazyXSelect': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/select/Select.vue")['default']
    'LazyXSkeleton': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/skeleton/Skeleton.vue")['default']
    'LazyXSlider': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/slider/Slider.vue")['default']
    'LazyXSpacer': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/spacer/Spacer")['default']
    'LazyXSpinner': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/spinner/Spinner.vue")['default']
    'LazyXStepper': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/stepper/Stepper.vue")['default']
    'LazyXTab': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/tab/Tab.vue")['default']
    'LazyXTabGroup': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/tab/TabGroup.vue")['default']
    'LazyXTable': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/table/Table.vue")['default']
    'LazyXTableBody': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/table/TableBody")['default']
    'LazyXTableCell': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/table/TableCell.vue")['default']
    'LazyXTableHead': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/table/TableHead.vue")['default']
    'LazyXTableHeader': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/table/TableHeader.vue")['default']
    'LazyXTableRow': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/table/TableRow.vue")['default']
    'LazyXTag': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/tag/Tag.vue")['default']
    'LazyXTextarea': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/textarea/Textarea.vue")['default']
    'LazyXThemeProvider': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/themeProvider/ThemeProvider.vue")['default']
    'LazyXToggle': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/toggle/Toggle.vue")['default']
    'LazyXTooltipToggleTip': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/tooltip/ToggleTip.vue")['default']
    'LazyXTooltip': typeof import("../../frontend/node_modules/@indielayer/ui/src/components/tooltip/Tooltip.vue")['default']
    'LazyNuxtWelcome': typeof import("../../frontend/node_modules/nuxt/dist/app/components/welcome")['default']
    'LazyNuxtLayout': typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../../frontend/node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../../frontend/node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../../frontend/node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtPage': typeof import("../../frontend/node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../../frontend/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const A6KnxLedLabeled: typeof import("../../frontend/components/a6-knx-led-labeled.vue")['default']
export const A6KnxLed: typeof import("../../frontend/components/a6-knx-led.vue")['default']
export const AppCarousel: typeof import("../../frontend/components/app-carousel.vue")['default']
export const BannerCustomize: typeof import("../../frontend/components/banner-customize.vue")['default']
export const ContentList: typeof import("../../frontend/components/content-list.vue")['default']
export const ElementsColorBox: typeof import("../../frontend/components/elements/color-box.vue")['default']
export const ElementsLinkBox: typeof import("../../frontend/components/elements/link-box.vue")['default']
export const Icon360: typeof import("../../frontend/components/icon/360.vue")['default']
export const MailchimpForm: typeof import("../../frontend/components/mailchimp-form.vue")['default']
export const MottoQuado: typeof import("../../frontend/components/motto-quado.vue")['default']
export const Motto: typeof import("../../frontend/components/motto.vue")['default']
export const ProductSample: typeof import("../../frontend/components/product-sample.vue")['default']
export const SwitchDesigner: typeof import("../../frontend/components/switch-designer.vue")['default']
export const SystemDeviceItem: typeof import("../../frontend/components/system-device-item.vue")['default']
export const Viewer3dModal: typeof import("../../frontend/components/viewer-3d-modal.vue")['default']
export const Viewer3d: typeof import("../../frontend/components/viewer-3d.vue")['default']
export const CookieControl: typeof import("../../frontend/node_modules/@dargmuesli/nuxt-cookie-control/dist/runtime/components/CookieControl.vue")['default']
export const CookieIframe: typeof import("../../frontend/node_modules/@dargmuesli/nuxt-cookie-control/dist/runtime/components/CookieIframe.vue")['default']
export const XAccordion: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/accordion/Accordion.vue")['default']
export const XAccordionItem: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/accordion/AccordionItem.vue")['default']
export const XAlert: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/alert/Alert.vue")['default']
export const XAvatar: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/avatar/Avatar.vue")['default']
export const XBadge: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/badge/Badge.vue")['default']
export const XBreadcrumbs: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/breadcrumbs/Breadcrumbs.vue")['default']
export const XButton: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/button/Button.vue")['default']
export const XButtonGroup: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/button/ButtonGroup.vue")['default']
export const XCard: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/card/Card.vue")['default']
export const XCarousel: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/carousel/Carousel.vue")['default']
export const XCarouselSlide: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/carousel/CarouselSlide.vue")['default']
export const XCheckbox: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/checkbox/Checkbox.vue")['default']
export const XContainer: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/container/Container.vue")['default']
export const XDatepicker: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/datepicker/Datepicker.vue")['default']
export const XDivider: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/divider/Divider.vue")['default']
export const XDrawer: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/drawer/Drawer.vue")['default']
export const XForm: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/form/Form.vue")['default']
export const XFormGroup: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/formGroup/FormGroup.vue")['default']
export const XIcon: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/icon/Icon.vue")['default']
export const XImage: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/image/Image.vue")['default']
export const XInput: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/input/Input.vue")['default']
export const XInputFooter: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/inputFooter/InputFooter.vue")['default']
export const XLabel: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/label/Label.vue")['default']
export const XLink: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/link/Link.vue")['default']
export const XLoader: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/loader/Loader.vue")['default']
export const XMenu: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/menu/Menu.vue")['default']
export const XMenuItem: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/menu/MenuItem.vue")['default']
export const XModal: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/modal/Modal.vue")['default']
export const XNotifications: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/notifications/Notifications.vue")['default']
export const XPagination: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/pagination/Pagination.vue")['default']
export const XPaginationItem: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/pagination/PaginationItem.vue")['default']
export const XPopover: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/popover/Popover.vue")['default']
export const XPopoverContainer: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/popover/PopoverContainer.vue")['default']
export const XProgress: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/progress/Progress.vue")['default']
export const XQrCode: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/qrCode/QrCode.vue")['default']
export const XRadio: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/radio/Radio.vue")['default']
export const XScroll: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/scroll/Scroll.vue")['default']
export const XSelect: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/select/Select.vue")['default']
export const XSkeleton: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/skeleton/Skeleton.vue")['default']
export const XSlider: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/slider/Slider.vue")['default']
export const XSpacer: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/spacer/Spacer")['default']
export const XSpinner: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/spinner/Spinner.vue")['default']
export const XStepper: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/stepper/Stepper.vue")['default']
export const XTab: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/tab/Tab.vue")['default']
export const XTabGroup: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/tab/TabGroup.vue")['default']
export const XTable: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/table/Table.vue")['default']
export const XTableBody: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/table/TableBody")['default']
export const XTableCell: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/table/TableCell.vue")['default']
export const XTableHead: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/table/TableHead.vue")['default']
export const XTableHeader: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/table/TableHeader.vue")['default']
export const XTableRow: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/table/TableRow.vue")['default']
export const XTag: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/tag/Tag.vue")['default']
export const XTextarea: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/textarea/Textarea.vue")['default']
export const XThemeProvider: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/themeProvider/ThemeProvider.vue")['default']
export const XToggle: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/toggle/Toggle.vue")['default']
export const XTooltipToggleTip: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/tooltip/ToggleTip.vue")['default']
export const XTooltip: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/tooltip/Tooltip.vue")['default']
export const NuxtWelcome: typeof import("../../frontend/node_modules/nuxt/dist/app/components/welcome")['default']
export const NuxtLayout: typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../../frontend/node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../../frontend/node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../../frontend/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../../frontend/node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../../frontend/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyA6KnxLedLabeled: typeof import("../../frontend/components/a6-knx-led-labeled.vue")['default']
export const LazyA6KnxLed: typeof import("../../frontend/components/a6-knx-led.vue")['default']
export const LazyAppCarousel: typeof import("../../frontend/components/app-carousel.vue")['default']
export const LazyBannerCustomize: typeof import("../../frontend/components/banner-customize.vue")['default']
export const LazyContentList: typeof import("../../frontend/components/content-list.vue")['default']
export const LazyElementsColorBox: typeof import("../../frontend/components/elements/color-box.vue")['default']
export const LazyElementsLinkBox: typeof import("../../frontend/components/elements/link-box.vue")['default']
export const LazyIcon360: typeof import("../../frontend/components/icon/360.vue")['default']
export const LazyMailchimpForm: typeof import("../../frontend/components/mailchimp-form.vue")['default']
export const LazyMottoQuado: typeof import("../../frontend/components/motto-quado.vue")['default']
export const LazyMotto: typeof import("../../frontend/components/motto.vue")['default']
export const LazyProductSample: typeof import("../../frontend/components/product-sample.vue")['default']
export const LazySwitchDesigner: typeof import("../../frontend/components/switch-designer.vue")['default']
export const LazySystemDeviceItem: typeof import("../../frontend/components/system-device-item.vue")['default']
export const LazyViewer3dModal: typeof import("../../frontend/components/viewer-3d-modal.vue")['default']
export const LazyViewer3d: typeof import("../../frontend/components/viewer-3d.vue")['default']
export const LazyCookieControl: typeof import("../../frontend/node_modules/@dargmuesli/nuxt-cookie-control/dist/runtime/components/CookieControl.vue")['default']
export const LazyCookieIframe: typeof import("../../frontend/node_modules/@dargmuesli/nuxt-cookie-control/dist/runtime/components/CookieIframe.vue")['default']
export const LazyXAccordion: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/accordion/Accordion.vue")['default']
export const LazyXAccordionItem: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/accordion/AccordionItem.vue")['default']
export const LazyXAlert: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/alert/Alert.vue")['default']
export const LazyXAvatar: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/avatar/Avatar.vue")['default']
export const LazyXBadge: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/badge/Badge.vue")['default']
export const LazyXBreadcrumbs: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/breadcrumbs/Breadcrumbs.vue")['default']
export const LazyXButton: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/button/Button.vue")['default']
export const LazyXButtonGroup: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/button/ButtonGroup.vue")['default']
export const LazyXCard: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/card/Card.vue")['default']
export const LazyXCarousel: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/carousel/Carousel.vue")['default']
export const LazyXCarouselSlide: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/carousel/CarouselSlide.vue")['default']
export const LazyXCheckbox: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/checkbox/Checkbox.vue")['default']
export const LazyXContainer: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/container/Container.vue")['default']
export const LazyXDatepicker: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/datepicker/Datepicker.vue")['default']
export const LazyXDivider: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/divider/Divider.vue")['default']
export const LazyXDrawer: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/drawer/Drawer.vue")['default']
export const LazyXForm: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/form/Form.vue")['default']
export const LazyXFormGroup: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/formGroup/FormGroup.vue")['default']
export const LazyXIcon: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/icon/Icon.vue")['default']
export const LazyXImage: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/image/Image.vue")['default']
export const LazyXInput: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/input/Input.vue")['default']
export const LazyXInputFooter: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/inputFooter/InputFooter.vue")['default']
export const LazyXLabel: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/label/Label.vue")['default']
export const LazyXLink: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/link/Link.vue")['default']
export const LazyXLoader: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/loader/Loader.vue")['default']
export const LazyXMenu: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/menu/Menu.vue")['default']
export const LazyXMenuItem: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/menu/MenuItem.vue")['default']
export const LazyXModal: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/modal/Modal.vue")['default']
export const LazyXNotifications: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/notifications/Notifications.vue")['default']
export const LazyXPagination: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/pagination/Pagination.vue")['default']
export const LazyXPaginationItem: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/pagination/PaginationItem.vue")['default']
export const LazyXPopover: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/popover/Popover.vue")['default']
export const LazyXPopoverContainer: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/popover/PopoverContainer.vue")['default']
export const LazyXProgress: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/progress/Progress.vue")['default']
export const LazyXQrCode: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/qrCode/QrCode.vue")['default']
export const LazyXRadio: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/radio/Radio.vue")['default']
export const LazyXScroll: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/scroll/Scroll.vue")['default']
export const LazyXSelect: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/select/Select.vue")['default']
export const LazyXSkeleton: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/skeleton/Skeleton.vue")['default']
export const LazyXSlider: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/slider/Slider.vue")['default']
export const LazyXSpacer: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/spacer/Spacer")['default']
export const LazyXSpinner: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/spinner/Spinner.vue")['default']
export const LazyXStepper: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/stepper/Stepper.vue")['default']
export const LazyXTab: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/tab/Tab.vue")['default']
export const LazyXTabGroup: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/tab/TabGroup.vue")['default']
export const LazyXTable: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/table/Table.vue")['default']
export const LazyXTableBody: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/table/TableBody")['default']
export const LazyXTableCell: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/table/TableCell.vue")['default']
export const LazyXTableHead: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/table/TableHead.vue")['default']
export const LazyXTableHeader: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/table/TableHeader.vue")['default']
export const LazyXTableRow: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/table/TableRow.vue")['default']
export const LazyXTag: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/tag/Tag.vue")['default']
export const LazyXTextarea: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/textarea/Textarea.vue")['default']
export const LazyXThemeProvider: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/themeProvider/ThemeProvider.vue")['default']
export const LazyXToggle: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/toggle/Toggle.vue")['default']
export const LazyXTooltipToggleTip: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/tooltip/ToggleTip.vue")['default']
export const LazyXTooltip: typeof import("../../frontend/node_modules/@indielayer/ui/src/components/tooltip/Tooltip.vue")['default']
export const LazyNuxtWelcome: typeof import("../../frontend/node_modules/nuxt/dist/app/components/welcome")['default']
export const LazyNuxtLayout: typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../../frontend/node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../../frontend/node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../../frontend/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtPage: typeof import("../../frontend/node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../../frontend/node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../../frontend/node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../../frontend/node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
