// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type IsAny<T> = 0 extends 1 & T ? true : false
type InjectionType<A extends Plugin> = IsAny<A> extends true ? unknown : A extends Plugin<infer T> ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../../frontend/node_modules/nuxt/dist/app/plugins/payload.client").default> &
  InjectionType<typeof import("../../../frontend/node_modules/nuxt/dist/app/plugins/navigation-repaint.client").default> &
  InjectionType<typeof import("../../../frontend/node_modules/nuxt/dist/app/plugins/check-outdated-build.client").default> &
  InjectionType<typeof import("../../../frontend/node_modules/nuxt/dist/app/plugins/revive-payload.server").default> &
  InjectionType<typeof import("../../../frontend/node_modules/nuxt/dist/app/plugins/revive-payload.client").default> &
  InjectionType<typeof import("../../../frontend/node_modules/nuxt/dist/app/plugins/chunk-reload.client").default> &
  InjectionType<typeof import("../../../frontend/node_modules/nuxt/dist/head/runtime/plugins/unhead").default> &
  InjectionType<typeof import("../../../frontend/node_modules/nuxt/dist/pages/runtime/plugins/router").default> &
  InjectionType<typeof import("../../../frontend/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client").default> &
  InjectionType<typeof import("../../../frontend/node_modules/@indielayer/ui/exports/nuxt.plugin").default> &
  InjectionType<typeof import("../../../frontend/node_modules/@zadigetvoltaire/nuxt-gtm/dist/runtime/plugin").default> &
  InjectionType<typeof import("../../../frontend/node_modules/@dargmuesli/nuxt-cookie-control/dist/runtime/plugin").default> &
  InjectionType<typeof import("../../../frontend/plugins/bg-image").default> &
  InjectionType<typeof import("../../../frontend/plugins/breakpoint").default> &
  InjectionType<typeof import("../../../frontend/plugins/firebase.client").default> &
  InjectionType<typeof import("../../../frontend/plugins/vue-color.client").default> &
  InjectionType<typeof import("../../../frontend/plugins/vue-intersect.cilent").default> &
  InjectionType<typeof import("../../../frontend/plugins/vue-lax").default> &
  InjectionType<typeof import("../../../frontend/plugins/vue-scroll-behavior").default> &
  InjectionType<typeof import("../../../frontend/plugins/vue-smooth-scroll.client").default> &
  InjectionType<typeof import("../../../frontend/plugins/vue-src").default> &
  InjectionType<typeof import("../../../frontend/plugins/vue3-parallax.client").default>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'nuxt:payload' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | 'nuxt:global-components' | 'nuxt:prefetch'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
